DiscStore/Controllers/DiscsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DiscStore.Models;

namespace DiscStore.Controllers
{
    public class DiscsController : Controller
    {
        private DiscStoreContext db = new DiscStoreContext();


        public ActionResult Index()
        {
            return RedirectToAction("Manage");
        }
        public ActionResult Manage()
        {
            if (User.IsInRole("admin"))
            {
                var discs = db.Discs.Include(d => d.Artists).Include(d => d.Genres);
                return View(discs.ToList());
            }
            else
            {
                return new HttpStatusCodeResult(403, "Forbidden!");
            }
        }

        public List<Disc> Filter(int artistID)
        {
            return db.Discs.Where(disc => disc.Artists.ArtistID == artistID).ToList<Disc>();
        }

        // GET: Discs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Disc disc = db.Discs.Find(id);
            if (disc == null)
            {
                return HttpNotFound();
            }
            return View(disc);
        }

        // GET: Discs/Create
        public ActionResult Create()
        {
            if (User.IsInRole("admin"))
            {
                ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "Name");
                ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName");
                return View();
            }
            else
            {
                return new HttpStatusCodeResult(403, "Forbidden!");
            }
        }

        // POST: Discs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DiscID,Name,ArtistID,GenreID,Price,IssueDate,ImgPath")] Disc disc)
        {
            if (User.IsInRole("admin"))
            {
                if (ModelState.IsValid)
                {
                    db.Discs.Add(disc);
                    db.SaveChanges();
                    return RedirectToAction("Manage");
                }

                ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "Name", disc.ArtistID);
                ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", disc.GenreID);
                return View(disc);
            }
            else
            {
                return new HttpStatusCodeResult(403, "Forbidden!");
            }
        }

        [HttpPost]
        public ActionResult AddDisc(int discID, string actionName)
        {
            Disc disc = db.Discs.Include("Artists").Include("Genres").First(a => a.DiscID == discID);
            if (Session["UserOrder"] != null)
                {
                    List<Disc> myOrders = (List<Disc>)Session["UserOrder"];
                    myOrders.Add(disc);
                    Session["UserOrder"] = myOrders;
                }
                else
                {
                    Session["UserOrder"] = new List<Disc> { disc };
                }

            return RedirectToAction(actionName);
        }

        [HttpPost]
        public ActionResult DelItem(Disc item, string actionName)
        {
            var itemToDelete = db.Discs.Where(x => x.DiscID == item.DiscID).FirstOrDefault();
            db.Discs.Remove(itemToDelete);
            db.SaveChanges();

            return RedirectToAction(actionName);
        }

        // GET: Discs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (User.IsInRole("admin"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Disc disc = db.Discs.Find(id);
                if (disc == null)
                {
                    return HttpNotFound();
                }
                ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "Name", disc.ArtistID);
                ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", disc.GenreID);
                return View(disc);
            }
            else
            {
                return new HttpStatusCodeResult(403, "Forbidden!");
            }
        }

        // POST: Discs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DiscID,Name,ArtistID,GenreID,Price,IssueDate,ImgPath")] Disc disc)
        {
            if (User.IsInRole("admin"))
            {
                if (ModelState.IsValid)
                {
                    db.Entry(disc).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Manage");
                }
                ViewBag.ArtistID = new SelectList(db.Artists, "ArtistID", "Name", disc.ArtistID);
                ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "GenreName", disc.GenreID);
                return View(disc);
            }
            else
            {
                return new HttpStatusCodeResult(403, "Forbidden!");
            }
        }

        // GET: Discs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (User.IsInRole("admin"))
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Disc disc = db.Discs.Find(id);
                if (disc == null)
                {
                    return HttpNotFound();
                }
                return View(disc);
            }
            else
            {
                return new HttpStatusCodeResult(403, "Forbidden!");
            }
        }

        // POST: Discs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (User.IsInRole("admin"))
            {
                Disc disc = db.Discs.Find(id);
                db.Discs.Remove(disc);
                db.SaveChanges();
                return RedirectToAction("Manage");
            }
            else
            {
                return new HttpStatusCodeResult(403, "Forbidden!");
            }
        }

        public ActionResult GetPopDiscs(string artist,  int? maxPrice, string name)
        {
            return View("Index", FilterData("Pop", artist, maxPrice, name));
        }

        public ActionResult GetJazzDiscs(string artist,  int? maxPrice, string name)
        {
            return View("Index", FilterData("Jazz", artist, maxPrice, name));
        }

        public ActionResult GetHipHopDiscs(string artist,  int? maxPrice, string name)
        {
            return View("Index", FilterData("HipHop", artist, maxPrice, name));
        }

        public ActionResult GetRockDiscs(string artist,  int? maxPrice, string name)
        {
            return View("Index", FilterData("Rock", artist, maxPrice, name));
        }

        public ActionResult GetDiscs(string ganner = null, string artist = null, int? maxPrice = null, string name = null)
        {
          return View("Index", FilterData(ganner, artist, maxPrice, name));
        }

        private List<Disc> FilterData(string ganner, string artist,  int? maxPrice, string name)
        {
            var _discs = db.Discs.Where(x => true);

            if (name != null && name != "")
            {
                _discs = _discs.Where(x => x.Name.ToLower().Contains(name.ToLower()));
            }

            if (ganner != null && ganner != "")
            {
                _discs = _discs.Where(x => x.Genres.GenreName == ganner);
            }

            if (artist != null && artist != "")
            {
                //artist = artist.ToLower();
                _discs = _discs.Where(x => x.Artists.Name.ToLower().Contains(artist.ToLower()));
            }

            if (maxPrice.HasValue)
            {
                _discs = _discs.Where(x => x.Price <= maxPrice);
            }
            

            return _discs.ToList();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DiscStore/Controllers/ShoppingCartController.cs
using DiscStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DiscStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private DiscStoreContext db = new DiscStoreContext();

        // GET: ShoppingCart
        public ActionResult Index()
        {
            return View("Index", (List<Disc>)Session["UserOrder"]);
        }

        public ActionResult Checkout()
        {
            return View("Checkout", db.Stores.ToList());
        }

        [HttpPost]
        public ActionResult DeleteDisc(int discID, string actionName)
        {
            List<Disc> myOrders = (List<Disc>)Session["UserOrder"];

            if (discID != null)
            {
                var itemToRemove = myOrders.FirstOrDefault(r => r.DiscID == discID);
                myOrders.Remove(itemToRemove);
            }

            Session["UserOrder"] = myOrders;

            return RedirectToAction(actionName);
        }

        [HttpPost]
        public ActionResult GetTotalPrice()
        {
            double totalPrice = 0;

            if (Session["UserOrder"] != null)
            {
                ((List<Disc>)Session["UserOrder"]).ForEach(x => totalPrice += x.Price);
            }

            return Json(totalPrice);
        }

        [HttpPost]
        public ActionResult GetUserName()
        {
            int userId = (int)Session["UserID"];
            string name = db.Users.Where(x => x.UserID == userId).Select(x => x.UserName).ToList()[0];
            return Json(name);
        }

        public ActionResult SaveOrder(int store)
        {
            List<Order> newOrderItems = new List<Order>();
            int userId = (int)Session["UserID"];

            List<Disc> orderDiscs = (List<Disc>)Session["UserOrder"];
            Session["UserOrder"] = null;

            // Get the next ID
            int nextId = db.Orders.ToList().Count + 1;
            int orderId = nextId;

            foreach (Disc item in orderDiscs)
            {
                Order newOrderRow = new Order()
                {
                    ID = nextId,
                    OrderID = orderId,
                    UserID = userId,
                    OrderDate = DateTime.Now,
                    DiscID = item.DiscID,
                    StoreID = store
                };

                newOrderItems.Add(newOrderRow);
                nextId++;
            }


            newOrderItems.ForEach(orderRow =>
            {
                db.Orders.Add(orderRow);
                db.SaveChanges();
            });

            return View("Completed");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DiscStore/Views/ShoppingCart/Checkout.cshtml
@model IEnumerable<DiscStore.Models.Store>
@{
    ViewBag.Title = "Checkout";
}
@section Scripts {
    <script type="text/javascript">$(document).ready(function () {
			getUserName();
			getTotalOrderPrice();
		});

		function getUserName() {
			$.ajax({
				type: "POST",
				url: '/ShoppingCart/GetUserName',
				success: function (res) {
					$("#userName").html('Hey, ' + res + '!');
				}
			});
		}

		function getTotalOrderPrice() {
			$.ajax({
				type: "POST",
				url: '/ShoppingCart/GetTotalPrice',
				success: function (res) {
					$("#price").html('You\'re total order price is ' + res.toFixed(2) + '₪');
				}
			});
		}

		$('form').submit(function () {
			if (!$('#store').val()) {
				alert('Choose a store to continue');
				return false;
			}

			return true;
        });

        function submitOrder(storeId) {
                $.ajax({
                    type: "POST",
                    url: '/ShoppingCart/SaveOrder',
                    data: {
                        store: storeId
                    } 
                });
            });
        });

    </script>
}
    <div style="text-align: center;">
        <h2>Checkout</h2>
        <h4 id="userName"></h4>
        <p id="price"></p>
        <p>Please choose the store you want to pick to order from:</p>
        @using (Html.BeginForm("SaveOrder", "ShoppingCart", FormMethod.Get))
        {
            <div class="row">
                <select name="store" id="store" class="selectpicker" data-style="btn-danger"
                        multiple data-max-options="3">
                    @foreach (var item in Model)
                    {
                        <option value="@item.ID">@item.Name</option>
                    }
                </select>
            </div>

            <div class="row">
                <input onsubmit="checkForm()" type="submit" style="width: 150px; margin-top:15px;" class="btn btn-primary" value="Submit the order" />
            </div>
        }
        </section>
    </div>

DiscStore/Views/ShoppingCart/Completed.cshtml
<div style="text-align: center">
    <h4> Your order was completed <i class="glyphicon glyphicon-ok"></i></h4>
    <p> It will arrive to the selected pickup point up to 5 business days </p>
</div>

DiscStore/Views/ShoppingCart/Index.cshtml
@model IEnumerable<DiscStore.Models.Disc>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Index";
    Session["your_array"] = new double[] { 1.0, 2.0, 3.0 };
}
@section Scripts {
    <script type="text/javascript">
        function deleteFromCart(discID, actionName) {
            $.ajax({
                type: "POST",
                url: '/ShoppingCart/DeleteDisc',
                data: {
                    discID: discID,
                    actionName: actionName
                },
                success: function () {
                    window.location.reload();
                }
            });
        }

        window.onload = function () {
            $.ajax({
                type: "POST",
                url: '/ShoppingCart/GetTotalPrice',
                success: function (res) {
                    $("#totalPrice").html(res+ '₪');
                }
            });
        }
    </script>
}
<div style="text-align: center;">
    <h2>Your Order Cart:</h2>
</div>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <!------ Need TO ADD TO THIS IF WHETER THE LIST IS EMPTY ---------->
    @if (Session["UserOrder"] == null || Model?.Count() == 0)
    {
        <h1>Is still empty! Go Shopping </h1>
    }
    else
    {
        <table id="cart" class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th style="width:50%">Disc</th>
                    <th style="width:10%">Artist</th>
                    <th style="width:10%">Genre</th>
                    <th style="width:10%">Quantity</th>
                    <th style="width:10%" class="text-center">Price</th>
                    <th style="width:10%"></th>
                </tr>
            </thead>
            <div class="displayRow">
                <tbody>
                        @foreach (var disc in ((List<DiscStore.Models.Disc>)Session["UserOrder"]).GroupBy(x => x.DiscID).Select(x => x.FirstOrDefault()))
                        {
                            <tr>
                                <td data-th="Disc">
                                    <div class="row">
                                        <div class="col-sm-2 hidden-xs"><img src="@Url.Content(disc.ImgPath)" alt="..." class="img-responsive" /></div>
                                        <div class="col-sm-10">
                                            <h4 class="nomargin">@disc.Name</h4>
                                        </div>
                                    </div>
                                </td>
                                <td data-th="Artist">@disc.Artists.Name</td>
                                <td data-th="Genre">@disc.Genres.GenreName</td>
                                <td data-th="Quantity"> @Model.Count(x => x.DiscID == disc.DiscID)</td>
                                <td data-th="Price" class="text-center">@disc.Price.ToString("0.00") ₪</td>
                                <td class="actions" data-th="">
                                    <button class="btn btn-danger btn-sm" onclick='deleteFromCart("@disc.DiscID", "@HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString()")'><i class="fa fa-trash-o"></i></button>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </div>
            <tfoot>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td><strong>Total </strong></td>
                    <td class="hidden-xs text-center"><strong id="totalPrice">Total </strong></td>
                    <td>
                        <a href='@Url.Action("Checkout", "ShoppingCart")' class="btn btn-success btn-block">
                            <i class="fa fa-angle-right"></i> Checkout
                        </a>
                    </td>
                </tr>
            </tfoot>
        </table>
    }

    @if (Session["UserOrder"] == null || Model?.Count() == 0)
    {
        <a href='@Url.Action("AllDiscs", "Discs")' class="btn btn-warning"><i class="fa fa-angle-left"></i> Start Shopping</a>
    }
    else
    {
        <a href='@Url.Action("AllDiscs", "Discs")' class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a>
    }
</div>