DiscStore/Controllers/LoginController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DiscStore.Models;
using System.Security.Claims;


namespace DiscStore.Controllers
{
    public class LoginController : Controller
    {
        private DiscStoreContext db = new DiscStoreContext();

        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }

        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string userName, string password)
        {
            var user = db.Users.Where(x => x.UserName == userName && x.Password == password).FirstOrDefault();

            if (user != null)
            {
                SignIn(userName, user.isAdmin);
                Session["UserID"] = user.UserID;
                return Json(new { Success = true });
            }
            else
            {
                return new HttpStatusCodeResult(410, "Unable to find user.");
            }
        }

        private void SignIn(string userName, bool isAdmin)
        {
            var claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Name, userName));
            claims.Add(new Claim(ClaimTypes.Role, isAdmin ? "admin" : "user"));
            var id = new ClaimsIdentity(claims, DefaultAuthenticationTypes.ApplicationCookie);

            AuthenticationManager.SignIn(id);
        }

        [HttpGet]
        public ActionResult Logout()
        {
            AuthenticationManager.SignOut();
            Session["UserID"] = null;
            Session["UserOrder"] = null;
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult IsAdmin()
        {
            AuthenticationManager.SignOut();
            Session["UserID"] = null;
            Session["UserOrder"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

DiscStore/Controllers/MapController.cs
using DiscStore.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DiscStore.Controllers
{
    public class MapController : Controller
    {
        private DiscStoreContext db = new DiscStoreContext();

        // GET: Map
        public ActionResult Index()
        {
            return View();
        }

        public string GetStores()
        {
            List<Store> StoresJson = new List<Store>();

            // Run over all the stores
            foreach (Store curr in db.Stores)
            {
                // Adding the current store
                StoresJson.Add(curr);
            }

            return JsonConvert.SerializeObject(StoresJson);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DiscStore/Controllers/ShoppingCartController.cs
using DiscStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DiscStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private DiscStoreContext db = new DiscStoreContext();

        // GET: ShoppingCart
        public ActionResult Index()
        {
            return View("Index", (List<Disc>)Session["UserOrder"]);
        }

        public ActionResult Checkout()
        {
            return View("Checkout", db.Stores.ToList());
        }

        [HttpPost]
        public ActionResult DeleteDisc(int discID, string actionName)
        {
            List<Disc> myOrders = (List<Disc>)Session["UserOrder"];

            if (discID != null)
            {
                var itemToRemove = myOrders.FirstOrDefault(r => r.DiscID == discID);
                myOrders.Remove(itemToRemove);
            }

            Session["UserOrder"] = myOrders;

            return RedirectToAction(actionName);
        }

        [HttpPost]
        public ActionResult GetTotalPrice()
        {
            double totalPrice = 0;

            if (Session["UserOrder"] != null)
            {
                ((List<Disc>)Session["UserOrder"]).ForEach(x => totalPrice += x.Price);
            }

            return Json(totalPrice);
        }

        [HttpPost]
        public ActionResult GetUserName()
        {
            int userId = (int)Session["UserID"];
            string name = db.Users.Where(x => x.UserID == userId).Select(x => x.UserName).ToList()[0];
            return Json(name);
        }

        public ActionResult SaveOrder(int store)
        {
            List<Order> newOrderItems = new List<Order>();
            int userId = (int)Session["UserID"];

            List<Disc> orderDiscs = (List<Disc>)Session["UserOrder"];
            Session["UserOrder"] = null;

            // Get the next ID
            int nextId = db.Orders.ToList().Count + 1;
            int orderId = nextId;

            foreach (Disc item in orderDiscs)
            {
                Order newOrderRow = new Order()
                {
                    ID = nextId,
                    OrderID = orderId,
                    UserID = userId,
                    OrderDate = DateTime.Now,
                    DiscID = item.DiscID,
                    StoreID = store
                };

                newOrderItems.Add(newOrderRow);
                nextId++;
            }


            newOrderItems.ForEach(orderRow =>
            {
                db.Orders.Add(orderRow);
                db.SaveChanges();
            });

            return View("Completed");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DiscStore/Controllers/StatisticsController.cs
using DiscStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DiscStore.Controllers
{
    public class StatisticsController : Controller
    {
        private DiscStoreContext db = new DiscStoreContext();

        // GET: Statistics
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetOrdersByGenre()
        {
            var ordersByGenre = db.Orders.Join(db.Discs,
                o => o.DiscID,
                d => d.DiscID,
                (order, disc) => new
                {
                    ordID = order.ID,
                    gnrID = disc.GenreID
                })
                .Join(db.Genres,
                o => o.gnrID,
                g => g.GenreID,
                (order, genre) => new
                {
                    ordID = order.ordID,
                    GenreName = genre.GenreName
                })
                .GroupBy(o => new { o.GenreName })
                .Select(o => new
                {
                    name = o.Key.GenreName,
                    value = o.Count()
                })
                .OrderBy(o => o.value);
            var ordersCount = new List<int>();
            var genres = new List<string>();

            ordersByGenre.ToList().ForEach((item) =>
            {
                ordersCount.Add(item.value);
                genres.Add(item.name);
            });
            return Json(new { ordersCount = ordersCount, genres = genres, data = ordersByGenre}, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetDiscsBygenre()
        {
            var discsBygenre = db.Discs.Join(db.Genres,
                o => o.GenreID,
                d => d.GenreID,
                (disc, genre) => new
                {
                    discName = disc.Name,
                    genreName = genre.GenreName
                })
                .GroupBy(g => new { g.genreName })
                .Select(g => new
                {
                    name = g.Key.genreName,
                    value = g.Count()
                })
                .OrderBy(d => d.value);
            var discsCount = new List<int>();
            var genres = new List<string>();
            discsBygenre.ToList().ForEach((item) =>
            {
                discsCount.Add(item.value);
                genres.Add(item.name);
            });
            return Json(new { discsCount = discsCount, genres = genres, data = discsBygenre}, JsonRequestBehavior.AllowGet);
        }
    }
} 

DiscStore/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap.css")
    @Styles.Render("~/Content/Site.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="row">
        <div class="col-sm-4">
            <h4>Our top pick for today:</h4>
            <iframe allow="autoplay *; encrypted-media *;" frameborder="0" height="150" style="width:100%;max-width:400px;overflow:hidden;background:transparent;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/us/album/old-town-road-feat-rm-of-bts-seoul-town-road-remix/1474182253?i=1474182258&app=music"></iframe>
        </div>
        <div class="col-sm-4">
            <img class="center-img"  style="width:200px;" src="~/Images/logo.png" />
        </div>
    </div>
    <nav class="navbar navbar-inverse" style="margin:0">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/">DiscStore</a>
            </div>
            <ul class="nav navbar-nav">

                <li class="navbarItem @(ViewContext.RouteData.Values["Action"].ToString() == "GetDiscs" ?
                    "active" : "")">
                    @Html.ActionLink("Discs", "GetDiscs", "Discs")
                </li>

                @if (Request.IsAuthenticated)
                {
                    <li class="navbarItem @(ViewContext.RouteData.Values["controller"].ToString() == "Suggestions" && ViewContext.RouteData.Values["Action"].ToString() == "Index" ?
                            "active" : "")">
                        @Html.ActionLink("Recommended for you", "Index", "Suggestions")
                    </li>
                    if (User.IsInRole("admin"))
                    {
                        <li class="navbarItem @(ViewContext.RouteData.Values["controller"].ToString() == "Genres" && ViewContext.RouteData.Values["Action"].ToString() == "Manage" ?
                                        "active" : "")">
                            @Html.ActionLink("Manage Genres", "Manage", "Genres")
                        </li>
                        <li class="navbarItem @(ViewContext.RouteData.Values["controller"].ToString() == "Discs" && ViewContext.RouteData.Values["Action"].ToString() == "Manage" ?
                                        "active" : "")">
                            @Html.ActionLink("Manage Discs", "Manage", "Discs")
                        </li>
                        <li class="navbarItem @(ViewContext.RouteData.Values["controller"].ToString() == "Artists" && ViewContext.RouteData.Values["Action"].ToString() == "Manage" ?
                                        "active" : "")">
                            @Html.ActionLink("Manage Artists", "Manage", "Artists")
                        </li>
                        <li class="navbarItem @(ViewContext.RouteData.Values["controller"].ToString() == "Stores" && ViewContext.RouteData.Values["Action"].ToString() == "Manage" ?
                                        "active" : "")">
                            @Html.ActionLink("Manage Stores", "Manage", "Stores")
                        </li>
                    }
                }

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href='@Url.Action("Index", "Map")'>
                        <i class="glyphicon glyphicon-map-marker"></i>
                    </a>
                </li>
                <li>
                    <a href='@Url.Action("Info", "Home")'>
                        <i class="glyphicon glyphicon-info-sign"></i>
                    </a>
                </li>
                <li>
                    <a href='@Url.Action("Index", "ShoppingCart")'>
                        <i class="glyphicon glyphicon-shopping-cart"></i>
                    </a>
                </li>
                <li>
                    <a href='@Url.Action("Index", "Statistics")'>
                        <i class="glyphicon glyphicon glyphicon-stats"></i>
                    </a>
                </li>
                @if (!Request.IsAuthenticated)
                {
                    <li>
                        <a href="@Url.Action("Index", "Login")">
                            <span class="glyphicon glyphicon-log-in">
                            </span> Login
                        </a>
                    </li>
                }
                else
                {
                    <li>
                        <a href="@Url.Action("Logout", "Login")">
                            <span class="glyphicon glyphicon-log-out">
                            </span> Logout
                        </a>
                    </li>
                }
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer class="footer-copyright text-center py-3">
        Site by Noa, Lidor, Eden and Adi
    </footer>

        @Scripts.Render("~/Scripts/jquery-3.3.1.min.js")
        @Scripts.Render("~/Scripts/bootstrap.min.js")
        @RenderSection("scripts", required: false)
</body>
</html>